FROM mcr.microsoft.com/devcontainers/python:3.13-bookworm

# Set JAVA_HOME environment variable
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH="$JAVA_HOME/bin:$PATH"

# Install Java
RUN apt-get update \
    && apt-get install --yes --no-install-recommends \
    openjdk-17-jdk \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    pyspark
